  AWSTemplateFormatVersion: '2010-09-09'
  Transform: AWS::Serverless-2016-10-31
  Description: AWS Serverless Quarkus HTTP - org.sample.quarkus::quarkuslambda
  Globals:
    Api:
      BinaryMediaTypes:
        - "*/*"

  Resources:
    QuarkuslambdaNativeFunction:
      Type: AWS::Serverless::Function
      Properties:
        Handler: not.used.in.provided.runtimei
        Runtime: provided
        CodeUri: target/function.zip
        MemorySize: 512
        Policies: AWSLambdaBasicExecutionRole
        Timeout: 30
        Environment:
          Variables:
            DISABLE_SIGNAL_HANDLERS: true
